
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: farmdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/farmdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

networks:
  my_network: