services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: farmdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    image: usainbald/backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/farmdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: usainbald/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: usainbald/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
